In [10]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix,classification_report,r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [12]:
Task2=pd.read_excel(r"D:\kunal_cdac_blr_notes\ML\TASK_TWO.xlsx")

Task2

SUMMARY OUTPUT       Unnamed: 1      Unnamed: 2  \
0                     NaN              NaN             NaN   
1   Regression Statistics              NaN             NaN   
2              Multiple R         0.993861             NaN   
3                R Square          0.98776             NaN   
4       Adjusted R Square         0.984539             NaN   
5          Standard Error         3.452575             NaN   
6            Observations               25             NaN   
7                     NaN              NaN             NaN   
8                   ANOVA              NaN             NaN   
9                     NaN               df              SS   
10             Regression                5    18277.514737   
11               Residual               19      226.485263   
12                  Total               24         18504.0   
13                    NaN              NaN             NaN   
14                    NaN     Coefficients  Standard Error   
15              Intercept         -40.5429       11.324154   
16                   rain         0.112519        0.043427   
17                  water        -0.078869        0.037748   
18                   dust         0.287486         0.09777   
19                    air         0.438565        0.111414   
20                    mud         0.948056        0.038845   
21                    NaN              NaN             NaN   
22                    NaN              NaN             NaN   
23                    NaN              NaN             NaN   
24        RESIDUAL OUTPUT              NaN             NaN   
25                    NaN              NaN             NaN   
26            Observation  Predicted yield       Residuals   
27                      1       101.484161       -1.484161   
28                      2        20.553942       -0.553942   
29                      3        69.666926        0.333074   
30                      4         7.814346        2.185654   
31                      5         74.94411         0.05589   
32                      6         74.37623        -4.37623   
33                      7         69.81294         5.18706   
34                      8        92.039864        2.960136   
35                      9        54.844252       -4.844252   
36                     10        65.777401        4.222599   
37                     11       101.484161       -1.484161   
38                     12        20.553942       -0.553942   
39                     13        69.666926        0.333074   
40                     14         7.814346        2.185654   
41                     15         74.94411         0.05589   
42                     16         74.37623        -4.37623   
43                     17         69.81294         5.18706   
44                     18        92.039864        2.960136   
45                     19        54.844252       -4.844252   
46                     20        65.777401        4.222599   
47                     21        73.042488       -3.042488   
48                     22        12.315095       -2.315095   
49                     23        77.194484       -2.194484   
50                     24         69.87548         0.12452   
51                     25         74.94411         0.05589   

            Unnamed: 3  Unnamed: 4          Unnamed: 5 Unnamed: 6  \
0                  NaN         NaN                 NaN        NaN   
1                  NaN         NaN                 NaN        NaN   
2                  NaN         NaN                 NaN        NaN   
3                  NaN         NaN                 NaN        NaN   
4                  NaN         NaN                 NaN        NaN   
5                  NaN         NaN                 NaN        NaN   
6                  NaN         NaN                 NaN        NaN   
7                  NaN         NaN                 NaN        NaN   
8                  NaN         NaN                 NaN        NaN   
9                   MS           F

In [14]:
x=Task2[["rain","water","dust","air","mud"]]

KeyError: "None of [Index(['rain', 'water', 'dust', 'air', 'mud'], dtype='object')] are in the [columns]"

In [16]:
y=Task2['yield']

KeyError: 'yield'

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

In [ ]:
# vif=pd.DataFrame(Task2)

In [94]:
vif['features']=x.columns
vif['VIF'] = [variance_inflation_factor(x.values, i) for i in range(x.shape[1])]
vif['VIF']=round(vif['VIF'],2)
vif=vif.sort_values(by="VIF",ascending= False)
vif

In [98]:
coeff=model.coef_

intercept=model.intercept_

[ 0.11172609 -0.09376292  0.27327126  0.42684685  0.96675731]
-39.96535179439215


In [100]:
coeff

array([ 0.11172609, -0.09376292,  0.27327126,  0.42684685,  0.96675731])

In [102]:
intercept

-39.96535179439215

In [122]:
line_eq=coeff*[40]+intercept
line_eq

array([-35.49630809, -43.71586849, -29.03450142, -22.89147787,
        -1.29505956])

In [104]:
y_pred=model.predict(x_test)

In [106]:
y_pred

array([ 55.04165058,  69.12383776, 101.19138112,  69.34844508,
        19.90347616,  65.85964487,   7.18837672,  19.90347616])

In [108]:
data=pd.DataFrame({"Predicted":y_pred,"Actual":y_test})

In [110]:
data

Predicted  Actual
8    55.041651      50
16   69.123838      75
0   101.191381     100
23   69.348445      70
11   19.903476      20
9    65.859645      70
13    7.188377      10
1    19.903476      20

In [114]:
r2_score(y_pred,y_test)

0.9880605806788832

In [132]:
mae = mean_absolute_error(y_test, y_pred) 
mse = mean_squared_error(y_test, y_pred) 
rmse = mse

In [134]:
rmse

10.857229475310525

In [136]:
mae

2.4882218687802755

In [138]:
mse

10.857229475310525