In [17]:
# Linear Regression

import numpy as np

In [19]:
df1=np.array([2,3,4,5,6])
df2=np.array([75,82,93,89,98])

In [23]:
X_square=df1*df1

In [25]:
X_square


array([ 4,  9, 16, 25, 36])

In [27]:
xy=df1*df2

In [29]:
xy

array([150, 246, 372, 445, 588])

In [31]:
x_bar=df1.mean()

In [33]:
x_bar

4.0

In [35]:
#mean
y_bar=df2.mean()
y_bar

87.4

In [37]:
x_square_bar = X_square.mean()
x_square_bar

18.0

In [39]:
xy_bar=xy.mean()
xy_bar

360.2

In [41]:
#slope
ao=((xy_bar)-(x_bar*y_bar))/(x_square_bar-(x_bar*x_bar))
ao

5.299999999999983

In [43]:
#interpet
a1=y_bar - (ao*x_bar)
a1

66.20000000000007

In [45]:
import pandas as pd
df1=pd.DataFrame({'x':[2,3,4,5,6],
'y':[75,82,93,89,98]})

In [47]:
new=df1.to_csv("regx.csv",index=False)
new

In [49]:
from sklearn.linear_model import LinearRegression

In [82]:
x1 = np.array([10,15,7,10,8,12])
x2 = np.array([2015,2016,2017,2018,2019,2020])
y = np.array([250,400,180,160,200,350]).reshape(-1,1)

In [84]:
model=LinearRegression()
model.fit(x1.reshape(-1,1),y.reshape(-1,1))

LinearRegression()

In [86]:
a=model.coef_

In [88]:
b=model.intercept_

In [90]:
ypred=model.predict(y)

In [ ]:
ypred

In [75]:
line=a*15+b

In [77]:
line

array([[397.41935484]])